import "./refund.css";

export const metadata = {
  title: "glo — Refund Policy",
  description: "The 90-day refund window and request process for glo GL-01.",
};

const HTML = "\r\n\r\n\r\n\r\n\r\n\r\n<main class=\"ctr\" id=\"main\">\r\n  <div class=\"draft-banner\"><b>DRAFT</b> · This policy is a working draft pending legal review. Final language will be confirmed by counsel prior to public launch.</div>\r\n  <div class=\"ey\"><span class=\"dash\"></span>Legal</div>\r\n  <h1><em>Refund</em> policy.</h1>\r\n  <div class=\"meta\">Effective date: <b>2026-05-08</b> · Last updated: 2026-05-08</div>\r\n\r\n  <div class=\"highlight\">\r\n    <div class=\"big\">90 days.</div>\r\n    <div class=\"sub\">Full refund · including used product</div>\r\n    <p>If you've taken the protocol as written and aren't seeing change, we'd rather refund you than keep your money. No restocking fee, no need to return the empty sachets.</p>\r\n  </div>\r\n\r\n  <h2 id=\"refund\">The <em>refund window</em>.</h2>\r\n  <p><b>You have 90 days from the date of your first shipment</b> to request a full refund of any glo GL-01 order, including product you've already used. We refund to the original payment method within 5–10 business days of approval.</p>\r\n  <p>For multi-month orders, the 90-day window applies to the entire purchase.</p>\r\n\r\n  <h2 id=\"how\">How to <em>request</em>.</h2>\r\n  <p>Email <a class=\"link\" href=\"mailto:official@weglow.biz\">official@weglow.biz</a> from the address associated with your order. Include your order number (or the email used at checkout) and a brief note on what you tried. Once received in your first 90 days we will:</p>\r\n  <ol>\r\n    <li>Confirm receipt within one business day.</li>\r\n    <li>Approve the refund in most cases without follow-up.</li>\r\n    <li>Process the refund to your original payment method within 5–10 business days.</li>\r\n  </ol>\r\n  <p>No need to return product. We don't restock used canisters.</p>\r\n\r\n  <h2 id=\"conditions\">Reasonable <em>conditions</em>.</h2>\r\n  <ul>\r\n    <li><b>One refund per household, lifetime.</b> The 90-day full refund is intended for first-time customers who tried the protocol and found it didn't work for them.</li>\r\n    <li>Refunds requested after 90 days are reviewed case-by-case and not guaranteed.</li>\r\n    <li>If a shipment arrives damaged or is lost in transit, we replace it at our cost — separate from the refund policy. Contact us within 14 days of expected delivery.</li>\r\n    <li>Wholesale, bulk, gift card, and promotional-credit purchases follow separate terms communicated at the time of purchase.</li>\r\n  </ul>\r\n\r\n  <h2 id=\"contact\">Questions.</h2>\r\n  <p>SciCare answers within one business day, Monday–Friday Pacific time:</p>\r\n  <p><a class=\"link\" href=\"mailto:official@weglow.biz\">official@weglow.biz</a></p>\r\n</main>\r\n\r\n\r\n";

export default function Page() {
  return <div dangerouslySetInnerHTML={{ __html: HTML }} />;
}
